# Generated by Django 4.0.1 on 2022-01-26 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('write', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CsvLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('import_ok', 'Import_ok'), ('status_host', 'Status_host'), ('import_error', 'Import_error')], default='import_ok', max_length=20)),
                ('log_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CsvRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_hostname', models.CharField(max_length=50)),
                ('asset_ip_address', models.CharField(max_length=20)),
                ('vulnerability_title', models.CharField(max_length=120)),
                ('vulnerability_severity', models.CharField(max_length=20)),
                ('vulnerability_cvss', models.FloatField()),
                ('publication_date', models.DateField()),
                ('fix', models.BooleanField(default=False)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_rows', to='reader.csvfile')),
            ],
            options={
                'ordering': ['-publication_date', 'vulnerability_cvss'],
            },
        ),
    ]
