# Generated by Django 4.0.1 on 2022-01-26 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlog',
            name='log_who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_who', to=settings.AUTH_USER_MODEL),
        ),
    ]
